os: linux
dist: bionic
services: docker
env:
  matrix:
    - COMPILER="CONCORD_BFT_CONTAINER_CC=gcc CONCORD_BFT_CONTAINER_CXX=g++"
    - COMPILER="CONCORD_BFT_CONTAINER_CC=clang CONCORD_BFT_CONTAINER_CXX=clang++"
    - CI_BUILD_TYPE="BUILD_TYPE=-DCMAKE_BUILD_TYPE=RELEASE CI_TEST_STORAGE_TYPE=-DCI_TEST_STORAGE_TYPE=v1direct"
    - CI_BUILD_TYPE="BUILD_TYPE=-DCMAKE_BUILD_TYPE=RELEASE CI_TEST_STORAGE_TYPE=-DCI_TEST_STORAGE_TYPE=v2merkle"
    - CI_BUILD_TYPE="BUILD_TYPE=-DCMAKE_BUILD_TYPE=DEBUG CI_TEST_STORAGE_TYPE=-DCI_TEST_STORAGE_TYPE=v2merkle"
script:
  - make build ${COMPILER} ${CI_BUILD_TYPE} OMIT_TEST_OUTPUT=-DOMIT_TEST_OUTPUT=ON test
