name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
        fail-fast: false
        matrix:
            compiler:
                - "CONCORD_BFT_CONTAINER_CC=gcc CONCORD_BFT_CONTAINER_CXX=g++"
                - "CONCORD_BFT_CONTAINER_CC=clang CONCORD_BFT_CONTAINER_CXX=clang++"
            ci_build_type:
                - "BUILD_TYPE=-DCMAKE_BUILD_TYPE=RELEASE CI_TEST_STORAGE_TYPE=-DCI_TEST_STORAGE_TYPE=v1direct"
                - "BUILD_TYPE=-DCMAKE_BUILD_TYPE=RELEASE CI_TEST_STORAGE_TYPE=-DCI_TEST_STORAGE_TYPE=v2merkle"
                - "BUILD_TYPE=-DCMAKE_BUILD_TYPE=DEBUG CI_TEST_STORAGE_TYPE=-DCI_TEST_STORAGE_TYPE=v2merkle"
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Create artifact directory
          run: mkdir -p ${{ github.workspace }}/artifact
        - name: Configure core dump location
          run: |
            echo '/cores/core.%e.%p' | sudo tee /proc/sys/kernel/core_pattern
            mkdir -p ${{ github.workspace }}/artifact/cores/
            # Uncomment this is you want to login into the running session.
            # Please note that the build will block on this step.
            # Refer to https://github.com/marketplace/actions/debugging-with-tmate
            #- name: Setup tmate session
            #  uses: mxschmitt/action-tmate@v2
        - name: Build and test
        - shell: script -e -c {0}
          run: |
            unbuffer make build ${{ matrix.compiler }} ${{ matrix.ci_build_type }} OMIT_TEST_OUTPUT=-DOMIT_TEST_OUTPUT=OFF test 2>&1 | tee ${{ github.workspace }}/artifact/build.log;
            exit ${PIPESTATUS[0]}
        - name: Prepare artifacts
          if: failure()
          run: |
            sudo chown -R $USER:$GROUP ${PWD}/build
            mv ${PWD}/build ${{ github.workspace }}/artifact/
            ls -lh ${{ github.workspace }}/artifact/cores
            sudo chown -R $USER:$GROUP ${{ github.workspace }}/artifact/
        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          if: failure()
          with:
            name: artifacts-${{ matrix.compiler }}-${{ matrix.ci_build_type }}-${{ github.sha }}
            path: ${{ github.workspace }}/artifact/
